trimble-oss/modus-mobile-maui-components

- .github/workflows/codeql.yml
Note: The Continuous Integration / Build (push) Action failing is unrelated to this PR. :-)
> Create CodeQL Analysis GitHub Action

- DemoApp/DemoApp/Platforms/Windows/App.xaml
- Trimble.Modus.Components/Controls/BorderlessEntry/BorderlessEntryHandler.cs
Implemented entry without border using handlers and added a few lines inside Windows platform app.xaml file.
> 68 - Changes for code review

- Trimble.Modus.Components/Constant/ColorsConstant.cs
- Trimble.Modus.Components/Controls/Button/CustomButton.xaml.cs
- Trimble.Modus.Components/Controls/TMCard/TMCard.xaml.cs
- Trimble.Modus.Components/Controls/TMModal/TMModal.cs
- Trimble.Modus.Components/Controls/Toast/TMToastContents.xaml.cs
- Trimble.Modus.Components/Styles/Colors.xaml
Moved Colors dictionary to styles - Closes #116 
Added constant file to store color names
> 116 - Moved Colors dictionary to styles

- Trimble.Modus.Components/Controls/TMInput/TMNumberInput/TMNumberInput.xaml.cs
Fix an issue where Value property can be set only once
> Bugfix: NumberInput | Cannot set value more than once

- DemoApp/DemoApp/MainPage.xaml
> Fix ListView Not Visible in iOS (DemoApp MainPage)

- Trimble.Modus.Components/Constant/Constants.cs
- Trimble.Modus.Components/Controls/TMRadioButton/TMRadioButtonGroup.cs
Disable creation of radio button without text, Closes #146
> Disable creation of radio button without text

- DemoApp/DemoApp/Views/SliderSamplePage.xaml
- Trimble.Modus.Components/Controls/TMSlider/SliderCore.cs
Update Alternate labels
Add TickValue property
> Modify Slider labels

- DemoApp/DemoApp/Views/ButtonPage.xaml
- DemoApp/DemoApp/Views/ButtonSamplePage.xaml
- DemoApp/DemoApp/Views/CardPage.xaml
- DemoApp/DemoApp/Views/CardSamplePage.xaml
- DemoApp/DemoApp/Views/ChipsSamplePage.xaml
- DemoApp/DemoApp/Views/DisplayAlertSamplePage.xaml
- DemoApp/DemoApp/Views/ModalPage.xaml
- DemoApp/DemoApp/Views/ModalSamplePage.xaml
- DemoApp/DemoApp/Views/NumberInputPage.xaml
- DemoApp/DemoApp/Views/NumberInputSamplePage.xaml
- DemoApp/DemoApp/Views/PopupSamples/SamplePopupPage.xaml
- DemoApp/DemoApp/Views/TabViewItems/TabViewThree.xaml
- Trimble.Modus.Components/Controls/Button/TMButton.xaml
- Trimble.Modus.Components/Controls/Button/TMButton.xaml.cs
- Trimble.Modus.Components/Controls/TMModal/TMModalContents.xaml.cs
> Change Title to Text

- Trimble.Modus.Components/Controls/TMSlider/SliderCore.cs
> fix catastrophic issue in windows

- Trimble.Modus.Components/Controls/TMDataGrid/DataGrid.xaml
- Trimble.Modus.Components/Controls/TMDataGrid/DataGrid.xaml.cs
- Trimble.Modus.Components/Controls/TMDataGrid/DataGridColumn.cs
- Trimble.Modus.Components/Controls/TMDataGrid/DataGridRow.cs
Description: Closes #261 
- Optimized DataGrid based on main branch last updated on September 3, 2023. (Last commit: 36d00bfb3d54435c917c09199b11c5fd3888ae8e)
- Fixed row repeating issue
> DataGrid Optimizations #261

- DemoApp/DemoApp/ViewModels/ButtonPageViewModel.cs
- DemoApp/DemoApp/Views/ButtonSamplePage.xaml
- DemoApp/DemoApp/Views/ButtonSamplePage.xaml.cs
- Trimble.Modus.Components/Controls/Button/TMButton.xaml
- Trimble.Modus.Components/Controls/Button/TMButton.xaml.cs
- Trimble.Modus.Components/Handlers/TMButtonAndroidTouchHandler.cs
- Trimble.Modus.Components/Handlers/TMButtonWindowsTouchHandler.cs
- Trimble.Modus.Components/Handlers/TMButtoniOSTouchHandler.cs
> Add Loading feature button

- Trimble.Modus.Components/Controls/TMDataGrid/ColumnTypes/TextColumn.xaml
- Trimble.Modus.Components/Controls/TMDataGrid/DataGridColumn.cs
> Modify Column header ,add padding below to cell

- DemoApp/DemoApp/Views/BadgeSamplePage.xaml
- Trimble.Modus.Components/Controls/TMBadge/TMBadge.xaml
- Trimble.Modus.Components/Controls/TMBadge/TMBadge.xaml.cs
> Add Badge on top of Content

- Trimble.Modus.Components/Controls/TMBadge/TMBadge.xaml
- Trimble.Modus.Components/Controls/TMBadge/TMBadge.xaml.cs
- Trimble.Modus.Components/Controls/TMBadge/TMBadgeStyles.xaml
- Trimble.Modus.Components/Controls/TMBadge/TMBadgeStyles.xaml.cs
- Trimble.Modus.Components/Styles/DarkTheme.xaml
- Trimble.Modus.Components/Styles/LightTheme.xaml
- Trimble.Modus.Components/Trimble.Modus.Components.csproj
> Dark theme badge

- DemoApp/DemoApp/Views/MessageSamplePage.xaml
- Trimble.Modus.Components/Controls/Messages/MessageView.xaml
- Trimble.Modus.Components/Controls/Messages/MessageView.xaml.cs
- Trimble.Modus.Components/Controls/Messages/MessageViewStyles.xaml
- Trimble.Modus.Components/Controls/Messages/MessageViewStyles.xaml.cs
- Trimble.Modus.Components/Styles/DarkTheme.xaml
- Trimble.Modus.Components/Styles/LightTheme.xaml
Added dark theme support for message, closes #302 
Screenshot:
> Message Dark theme support - #302

- Trimble.Modus.Components/Controls/TMInput/InputTemplateResourceDictionary.xaml
- Trimble.Modus.Components/Handlers/EntryHandler.cs
This should remove the horizontal space displayed in #340
> Removes the padding in windows entry

- Trimble.Modus.Components/Controls/DropDown/TMDropDown.xaml
- Trimble.Modus.Components/Controls/DropDown/TMDropDown.xaml.cs
Fixed the UI like below
Fixed the UI like below
> Dropdown UI improvement - 359

- Trimble.Modus.Components/Controls/TabBar/TMTabbedPage.cs
- Trimble.Modus.Components/Controls/TabBar/TabViewItem.xaml
- Trimble.Modus.Components/Controls/TabBar/TabViewItem.xaml.cs
> Changes for supporting tabbed page in windows

- DemoApp/DemoApp/Views/PopupSamples/SampleCustomPopup.xaml.cs
- Trimble.Modus.Components/Controls/Popup/Animations/Base/BaseAnimation.cs
- Trimble.Modus.Components/Controls/Popup/Animations/Base/FadeBackgroundAnimation.cs
- Trimble.Modus.Components/Controls/Popup/Animations/MoveAnimation.cs
- Trimble.Modus.Components/Controls/Popup/Enums/MoveAnimationOptions.cs
- Trimble.Modus.Components/Controls/Popup/Pages/PopupPage.cs
Please check this ticket https://github.com/trimble-oss/modus-mobile-maui-components/issues/339
> Unable do animation for popup page #339

- DemoApp/DemoApp/ViewModels/DropDownSampleViewModel.cs
- DemoApp/DemoApp/ViewModels/SwitchViewModel.cs
- DemoApp/DemoApp/Views/DropDownSamplePage.xaml
- DemoApp/DemoApp/Views/SwitchSamplePage.xaml
- Trimble.Modus.Components/Controls/DropDown/TMDropDown.xaml
- Trimble.Modus.Components/Controls/DropDown/TMDropDown.xaml.cs
- Trimble.Modus.Components/Controls/Label/ControlLabel.xaml
- Trimble.Modus.Components/Controls/Label/ControlLabel.xaml.cs
- Trimble.Modus.Components/Controls/Label/ControlLabelStyles.xaml
- Trimble.Modus.Components/Controls/Label/ControlLabelStyles.xaml.cs
- Trimble.Modus.Components/Controls/Popup/Animations/RevealAnimation.cs
- Trimble.Modus.Components/Controls/Popup/Pages/PopupPage.cs
- Trimble.Modus.Components/Controls/TMInput/BaseInput.xaml.cs
- Trimble.Modus.Components/Controls/TMInput/InputTemplateResourceDictionary.xaml
- Trimble.Modus.Components/Controls/TMInput/MultiLineInput.xaml.cs
- Trimble.Modus.Components/Controls/TMInput/TMInput.xaml.cs
- Trimble.Modus.Components/Controls/TMSwitch/TMSwitch.xaml
- Trimble.Modus.Components/Controls/TMSwitch/TMSwitch.xaml.cs
- Trimble.Modus.Components/Enums/SwitchLabelPosition.cs
- Trimble.Modus.Components/Enums/TitlePosition.cs
- Trimble.Modus.Components/Trimble.Modus.Components.csproj
Changes for dropdown crash while closing the popup.
> Changes for dropdown crash and UI fix for ios

- Trimble.Modus.Components/Controls/TMInput/TMNumberInput.xaml
- Trimble.Modus.Components/Controls/TMInput/TMNumberInput.xaml.cs
- Trimble.Modus.Components/Controls/TMInput/TMNumberInputStyles.xaml
- Trimble.Modus.Components/Controls/TMInput/TMNumberInputStyles.xaml.cs
- Trimble.Modus.Components/Styles/DarkThemeColors.xaml
- Trimble.Modus.Components/Styles/DarkThemeStyling.xaml
- Trimble.Modus.Components/Styles/LightThemeColors.xaml
- Trimble.Modus.Components/Styles/LightThemeStyling.xaml
- Trimble.Modus.Components/Trimble.Modus.Components.csproj
Update color of the plus and minus icon in Number input when theme changes #400
> Update color of the plus and minus icon in Number input when theme changes - #400

- Trimble.Modus.Components/Controls/DropDown/TMDropDown.xaml.cs
Added scrollto for the listview to display a selected item when tapping dropdown
> Dropdown popup listview should scroll to the selected item #407

- Trimble.Modus.Components/Controls/DropDown/TMDropDown.xaml
- Trimble.Modus.Components/Controls/Label/ControlLabel.xaml
- Trimble.Modus.Components/Controls/Label/ControlLabel.xaml.cs
- Trimble.Modus.Components/Controls/Label/ControlLabelStyles.xaml
- Trimble.Modus.Components/Controls/Popup/Pages/PopupPage.cs
- Trimble.Modus.Components/Controls/TMInput/BaseInput.xaml
- Trimble.Modus.Components/Controls/TMInput/BaseInput.xaml.cs
- Trimble.Modus.Components/Controls/TMInput/TMInputStyles.xaml
- Trimble.Modus.Components/Styles/DarkThemeStyling.xaml
- Trimble.Modus.Components/Styles/LightThemeStyling.xaml
- Trimble.Modus.Components/Trimble.Modus.Components.csproj
Fixed - If TMDropdown and TMInput TitleText is empty or null, empty space is displaying in the top of the field
Fixed - ControlLabelStyle is not applied for ControlLabel, Changed the ControlLabel style name to DefaultControlLabelStyle, 
Fixed - Helper text color change
Fixed - https://github.com/trimble-oss/modus-mobile-maui-components/issues/415 - Modus dropdown popup is not displaying properly in android
Fixed - ControlLabel and * aligenment not matched
> Modus styling issues

- Trimble.Modus.Components/Controls/BorderlessEditor/BorderlessEditor.cs
- Trimble.Modus.Components/Controls/BorderlessEntry/BorderlessEntry.cs
- Trimble.Modus.Components/Handlers/EditorHandler.cs
- Trimble.Modus.Components/Handlers/EntryHandler.cs
- Trimble.Modus.Components/Handlers/LabelHandler.cs
.Net 9 apps we are getting compilation error in android specific code in the LabelHanlder, EntryHandler and EditorHandler classes.
Fixed those compilation error.
> 417 android app crash in net9

- Trimble.Modus.Components/Images/white_info_outline_icon.svg
- Trimble.Modus.Components/Styles/DarkThemeStyling.xaml
In dark mode we should display a white info icon under the entry field. I have added a white info icon and updated in DarkThemeStyling file
> Image color are not changing in dark mode #420
